"""company_fundamentals table + announcements.source column

Revision ID: 93dd6a13c006
Revises:
Create Date: 2026-07-17 01:24:37.601103

First-ever Alembic revision for this project. The other 10 tables were
created on the live Neon DB via Base.metadata.create_all() (init_db),
so this migration only applies the Phase 5 Session 2 delta:

1. New company_fundamentals table (PSX Terminal fundamentals snapshot,
   one row per ticker, all metrics nullable).
2. New announcements.source column (nullable) so PSX Terminal-mirrored
   announcements are distinguishable from the legacy PSX-portal scraper
   rows and from any future PUCARS-direct scraper.

Hand-written rather than autogenerated: an autogenerate diff against
the pre-existing create_all() schema risks dragging unrelated noise in;
the intended delta is exactly these two changes.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '93dd6a13c006'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "company_fundamentals",
        sa.Column(
            "id", postgresql.UUID(as_uuid=True), primary_key=True,
            nullable=False,
        ),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("pe_ratio", sa.Float(), nullable=True),
        sa.Column("dividend_yield", sa.Float(), nullable=True),
        sa.Column("market_cap_pkr", sa.Float(), nullable=True),
        sa.Column("free_float_pct", sa.Float(), nullable=True),
        sa.Column(
            "last_updated", sa.DateTime(timezone=True),
            server_default=sa.text("now()"), nullable=False,
        ),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(["ticker"], ["companies.ticker"]),
        sa.UniqueConstraint("ticker", name="uq_fundamentals_ticker"),
    )
    op.create_index(
        op.f("ix_company_fundamentals_ticker"),
        "company_fundamentals",
        ["ticker"],
    )

    op.add_column(
        "announcements",
        sa.Column("source", sa.String(length=50), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("announcements", "source")
    op.drop_index(
        op.f("ix_company_fundamentals_ticker"),
        table_name="company_fundamentals",
    )
    op.drop_table("company_fundamentals")
