"""
PSX Sentinel — Intelligence, Alert & Watchlist Schemas

Pydantic v2 models for intelligence reports, analysis job status,
user alerts, and watchlist management endpoints.
"""

import uuid
from datetime import date, datetime

from pydantic import BaseModel, ConfigDict, Field


class IntelligenceReportResponse(BaseModel):
    """Full intelligence report generated by the 4-agent system."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    ticker: str
    generated_at: datetime
    report_date: date
    ml_beat_probability: float
    conviction_score: float
    bull_case: str
    bear_case: str
    risk_factors: list[str]
    technical_signal: str
    total_tokens_used: int
    generation_time_seconds: float


class AnalysisJobResponse(BaseModel):
    """Status response for a queued or running analysis job."""

    job_id: str
    ticker: str
    status: str  # "queued" | "running" | "complete" | "failed"
    message: str
    estimated_seconds: int = 60


class AlertResponse(BaseModel):
    """User-configured price/conviction alert."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    ticker: str
    alert_type: str
    threshold_value: float | None
    is_active: bool
    triggered_count: int
    created_at: datetime


class CreateAlertRequest(BaseModel):
    """
    Request to create a new alert.

    alert_type must be one of: PRICE_ABOVE, PRICE_BELOW,
    CONVICTION_ABOVE, NEW_REPORT, EARNINGS_ANNOUNCEMENT.
    threshold_value is required for PRICE_* and CONVICTION_* types.
    """

    ticker: str = Field(min_length=1, max_length=20)
    alert_type: str = Field(
        pattern=r"^(PRICE_ABOVE|PRICE_BELOW|CONVICTION_ABOVE|NEW_REPORT|EARNINGS_ANNOUNCEMENT)$"
    )
    threshold_value: float | None = None


class WatchlistItemResponse(BaseModel):
    """Watchlist entry with optional company name from join."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    ticker: str
    company_name: str | None = None
    added_at: datetime
    notes: str | None


class AddWatchlistRequest(BaseModel):
    """Request to add a ticker to the user's watchlist."""

    ticker: str = Field(min_length=1, max_length=20)
    notes: str | None = Field(default=None, max_length=500)
